name: pitz
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.48105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f4959'
    - '#dedede'
    - '#6194a7'
    - '#9cbcc7'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.1247773829381913
purpose: []
